server:
  port: 8010  #访问端口
  session-timeout: 1800
  tomcat: #tomcat配置
    max-threads: 0
    uri-encoding: UTF-8
    basedir: target/tomcat

#Spring配置
spring:
  datasource: #数据库配置
    url : jdbc:mysql://:3306/alibb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username : root
    password : 
    driverClassName : com.mysql.jdbc.Driver
    # HTTP encoding (HttpEncodingProperties)
    http:
      encoding.charset: UTF-8
      encoding.enabled: true
      encoding.force: true

#MYBATIS配置
mybatis:
  type-aliases-package: com.springboot.alibb.mapper
  #mapper.xml所在位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30


#日志配置
logging:
  level:  #日志级别
    root: DEBUG   #优先级从高到低依次为：OFF、FATAL、ERROR、WARN、INFO、DEBUG、TRACE、 ALL。
